import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] %(levelname)s - %(message)s')

project_name = "chicken_disease_classifier"  # keep package names lowercase
temporal_project_name = "chicken_disease"  # keep package names lowercase

list_of_files = [
    Path(".github/workflows/.gitkeep"),
    Path("app/flask_api/app.py"),
    Path("app/streamlit_ui/app.py"),
    Path("app/flask_api/schemas.py"),
    Path("app/flask_api/utils.py"),
    Path("app/streamlit_ui/components.py"),
    Path("artifacts/model/model.pt"),
    Path("artifacts/model/class_map.json"),
    Path("artifacts/reports/metrics.json"),
    Path("artifacts/reports/confusion_matrix.png"),
    Path("artifacts/models/baseline_single.pt"),
    Path("artifacts/models/multi_image.pt"),
    Path("artifacts/models/class_map.json"),
    Path("artifacts/reports/robustness_tests.json"),
    Path("artifacts/reports/risk_trend_examples/.gitkeep"),
    Path("config/config.yaml"),
    Path("config/logging.yaml"),
    Path("data/raw/.gitkeep"),
    Path("data/raw/healthy/.gitkeep"),
    Path("data/raw/cocci/.gitkeep"),
    Path("data/raw/salmo/.gitkeep"),
    Path("data/raw/ncd/.gitkeep"),
    Path("data/interim/.gitkeep"),
    Path("data/processed/single/train/.gitkeep"),
    Path("data/processed/single/val/.gitkeep"),
    Path("data/processed/single/test/.gitkeep"),
    Path("data/processed/multi/train/.gitkeep"),
    Path("data/processed/multi/val/.gitkeep"),
    Path("data/processed/multi/test/.gitkeep"),
    Path("dvc.yaml"),
    Path("params.yaml"),
    Path("requirements.txt"),
    Path("setup.py"),
    Path("research/trials.ipynb"),
    Path("research/data_audit.ipynb"),
    Path("research/baseline_experiments.ipynb"),
    Path("research/temporal_analysis.ipynb"),
    Path("research/interpretability_checks.ipynb"),
    Path("README.md"),
    Path(f"src/{project_name}/__init__.py"),
    Path(f"src/{project_name}/components/__init__.py"),
    Path(f"src/{project_name}/components/ingest.py"),
    Path(f"src/{project_name}/components/preprocess.py"),
    Path(f"src/{project_name}/components/trainer.py"),
    Path(f"src/{project_name}/components/evaluator.py"),
    Path(f"src/{project_name}/config/__init__.py"),
    Path(f"src/{project_name}/config/configuration.py"),
    Path(f"src/{project_name}/constants/__init__.py"),
    Path(f"src/{project_name}/entity/__init__.py"),
    Path(f"src/{project_name}/entity/config_entity.py"),
    Path(f"src/{project_name}/pipeline/__init__.py"),
    Path(f"src/{project_name}/pipeline/stage_01_ingest.py"),
    Path(f"src/{project_name}/pipeline/stage_02_preprocess.py"),
    Path(f"src/{project_name}/pipeline/stage_03_train.py"),
    Path(f"src/{project_name}/pipeline/stage_04_evaluate.py"),
    Path(f"src/{project_name}/utils/__init__.py"),
    Path(f"src/{project_name}/utils/common.py"),
    Path(f"src/{temporal_project_name}/__init__.py"),
    Path(f"src/{temporal_project_name}/datasets/single_image.py"),
    Path(f"src/{temporal_project_name}/datasets/multi_image.py"),
    Path(f"src/{temporal_project_name}/models/encoder.py"),
    Path(f"src/{temporal_project_name}/models/attention_pool.py"),
    Path(f"src/{temporal_project_name}/models/temporal_gru.py"),
    Path(f"src/{temporal_project_name}/models/heads.py"),
    Path(f"src/{temporal_project_name}/losses/classification.py"),
    Path(f"src/{temporal_project_name}/losses/smoothness.py"),
    Path(f"src/{temporal_project_name}/losses/consistency.py"),
    Path(f"src/{temporal_project_name}/training/train_single.py"),
    Path(f"src/{temporal_project_name}/training/train_multi.py"),
    Path(f"src/{temporal_project_name}/training/callbacks.py"),
    Path(f"src/{temporal_project_name}/evaluation/metrics.py"),
    Path(f"src/{temporal_project_name}/evaluation/robustness.py"),
    Path(f"src/{temporal_project_name}/evaluation/early_warning.py"),
    Path(f"src/{temporal_project_name}/explainability/gradcam.py"),
    Path(f"src/{temporal_project_name}/explainability/temporal_saliency.py"),
    Path(f"src/{temporal_project_name}/explainability/sanity_checks.py"),
    Path(f"src/{temporal_project_name}/pipeline/stage_01_ingest.py"),
    Path(f"src/{temporal_project_name}/pipeline/stage_02_preprocess.py"),
    Path(f"src/{temporal_project_name}/pipeline/stage_03_train_single.py"),
    Path(f"src/{temporal_project_name}/pipeline/stage_04_train_multi.py"),
    Path(f"src/{temporal_project_name}/pipeline/stage_05_evaluate.py"),
    Path(f"src/{temporal_project_name}/utils/io.py"),
    Path(f"src/{temporal_project_name}/utils/image_ops.py"),
    Path(f"src/{temporal_project_name}/utils/config.py"),
    Path(f"src/{temporal_project_name}/utils/seed.py"),
]

for file_path in list_of_files:
    file_path.parent.mkdir(parents=True, exist_ok=True)

    if not file_path.exists():
        file_path.touch()
        logging.info(f"Created file: {file_path}")
    else:
        logging.info(f"Already exists: {file_path}")
