data:
  raw_dir: /mnt/scratch/kodumuru/pari/chicken_disease/data/raw
  interim_dir: /mnt/scratch/kodumuru/pari/chicken_disease/data/interim
  processed_dir: /mnt/scratch/kodumuru/pari/chicken_disease/data/processed

artifacts:
  model_dir: /mnt/scratch/kodumuru/pari/chicken_disease/models
  reports_dir: /mnt/scratch/kodumuru/pari/chicken_disease/reports
